FROM debian:bookworm-slim

RUN apt-get update

RUN apt-get -y install python3 python3-pip

RUN export DEBIAN_FRONTEND=noninteractive && apt-get -y install python3-tk # buildkit

RUN apt-get -y install network-manager # buildkit

RUN apt-get -y install curl cmake build-essential tcl-dev tk-dev # buildkit

RUN apt-get install -y x11-apps

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENV DISPLAY=host.docker.internal:0

RUN pip3 install xes-neo --break-system-packages
